api: "sncloud" #  set either sambastudio or sncloud

audio_model:
    "temperature": 0.0
    "language": "en"
    "select_expert": "whisper-large-v3"

llm: 
    "temperature": 0.0
    "do_sample": False
    "max_tokens_to_generate": 1200
    "coe": True #set as true if using Sambastudio CoE endpoint
    "select_expert": "llama3-8b" #set if using sncloud, SambaStudio CoE llm expert
    #sncloud CoE expert name -> "llama3-8b"

prod_mode: True
